### ISSUE TITLE
v2 Endpoints

### ISSUE THREAD

**Issue by emma144** [RandomCocc0nut/ShinyBank#1]
GET `/version` - this returns "v1" or "v2". This is actually also on the v1 website right now: [go try it yourself!](https://shinies.space/version)

GET `/api/users/__evelyn` - a user's balance, history, their dashboard pins (dashboard pins = a new feature in v2 where you can pin users on your dashboard), and their boolean admin status (true or false)
like this: `{"balance":0,"history":[{"type":"paid","user":"__evelyn","amount":10,"date":0},{"type":"received","user":"__evelyn","amount":10,"date":0}],"pins":["__evelyn","__evelyn","__evelyn"],"admin":true,"exists":true}`
or `{"exists":false}` if the user does not exist or hasn't registered their account

GET `/api/history/__evelyn` - a parsed history of a user in HTML, like this:
`{"exists":true,"html":"<br /><a href=\"/u/__evelyn\">__evelyn</a> paid you 10 shinies 57 years ago<br />You paid <a href=\"/u/__evelyn\">__evelyn</a> 10 shinies 57 years ago"}`
or just `{"exists":false}` if the user is not registered

GET `/api/app/2ewxkn2sm4` - basic info about an app ID. JSON Keys: exists (boolean), name (string), receiver (string)

POST `/api/pay` with body `{ "key": "__evelyn.194739021", "receiver": "RandomCocconut", "amount": 10 }`

POST `/api/app-pay` with body `{ "key": "__evelyn.194739021", "app": "2ewxkn2sm4", "amount": 10 }`
NOTE: a shinies admin will have to generate you an app ID, and the app ID automatically determines what it is called and who the receiver is.

remember, v2 isn't finished yet and the endpoints are subject to change

**Comment by RandomCocc0nut** [comment]
Updated it to 2.0 Api!
