### ISSUE TITLE
One thing you can do is

### ISSUE THREAD

**Issue by emma144** [RandomCocc0nut/ShinyBank#2]
check for the version. Fetch it - if it is v1, use the endpoints for v1. If it is v2, use the ones for v2

**Comment by RandomCocc0nut** [comment]
Would it not be useless when the new version will be released?

**Comment by emma144** [comment]
Well, for now it is very useful

**Comment by RandomCocc0nut** [comment]
Ok, tomorrow I will do it.

**Comment by RandomCocc0nut** [comment]
Done
